name: Test for badge

on: 
  pull_request:
    branches:
    - main
    - release/*

jobs:
  auto-assign:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Auto-assign issue
              run: |
                ls
